server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.103:5432/Greenhouse
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

